SELECT * FROM TAB;

SELECT * FROM COUNTRIES; -- 국가

SELECT * FROM DEPARTMENTS; -- 상품? 항목?

SELECT * FROM EMPLOYEES; -- 노동자 관련, DEPARTMENTS와 외래키(DEPARTMENT_ID) 존재 / EMPLOYEE_ID

SELECT * FROM EMP_DETAILS_VIEW; -- 노동자 세부항목,  EMPLOYEES와 외래키(JOB_ID) 존재

SELECT COUNT(JOB_TITLE)
FROM JOBS
ORDER BY JOB_TITLE;
-- 직업. EMP_DETAILS_VIEW와 외래키(JOB_ID)

SELECT * FROM JOB_HISTORY; -- 노동 이력? 외래키( EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID)

SELECT * FROM LOCATIONS; -- 장소? 위치? 외래키(COUNTRY_ID, LOCATION_ID)

SELECT * FROM REGIONS; -- 대륙. 외래키 (REGION_ID) -> 국가랑 연결.

-- 유럽 출력하기
SELECT * 
FROM COUNTRIES C, REGIONS R 
WHERE C.REGION_ID = R.REGION_ID AND REGION_NAME = 'Europe';

--Diana의 직업 출력
SELECT *
FROM EMPLOYEES; --Diana 이름, job_id

SELECT *
FROM JOBS; --job_id, 직업명

SELECT FIRST_NAME, JOB_TITLE
FROM EMPLOYEES E, JOBS J
WHERE E.JOB_ID = J.JOB_ID AND FIRST_NAME = 'Diana';

--HR/HR 계정 test
--16.?직원의 이름(LAST_NAME)과 직책(JOB_TITLE) 검색
--단, 사용되지 않는 직책이 있다면 그 직책이 정보도 검색에 포함 
--검색 정보 이름(2개 : LAST_NAME, First_NAME)과 job_title(직책)
SELECT LAST_NAME, First_NAME, JOB_TITLE
FROM EMPLOYEES E, JOBS J
WHERE E.JOB_ID = J.JOB_ID
ORDER BY JOB_TITLE;

--17.?직원들의 이름(First_NAME), 입사일, 부서명(DEPARTMENT_NAME) 검색
SELECT E.FIRST_NAME, E.HIRE_DATE, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;








